### PR TITLE
feat: Implementation and refactoring

### PR DESCRIPTION
**Pull request by selenehyun**
- Change wording: `language` -> `locale`
- Remove direction selector
- Add option: `directionResolver`
- Write `README.md`

https://www.npmjs.com/package/@ecubelabs/storybook-addon-intl

### CODE REVIEW

**Comment by selenehyun** [comment]
https://github.com/Ecube-Labs/storybook-addon-intl/tree/move-for-publish-package

**Comment by selenehyun** [comment]
https://storybook.js.org/addons/@ecubelabs/storybook-addon-intl/

**Comment by selenehyun** [comment]
@woq1124

**Comment by woq1124** [comment]
??? 제가 asignee 인가요?

**Comment by selenehyun** [comment]
@woq1124 넵 빈이 개발하신걸 제가 조금 손보고 배포했습니다 😄
리뷰해주세영

**Comment by woq1124** [comment]
리뷰 끝나면 Merge pull request 누르면 되나여?

**Comment by selenehyun** [comment]
> 리뷰 끝나면 Merge pull request 누르면 되나여?

Approved > Merge

**Review by woq1124 — APPROVED** [review]
수고하셨습니다.

**Pull request merged**
